version: '3.7'

services:
  nginx:
    container_name: nginx
    # https://github.com/oleksii-honchar/nginx-more
    image: tuiteraz/nginx-more:1.1.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../nginx/configs.loc:/etc/nginx:ro
    links:
      - "svc-auth:svc-auth"
      - "wa:wa"
    networks:
      - default
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10k"
        max-file: "3"

  wa:
    container_name: wa
    image: tuiteraz/auth-app-2019-wa:latest
    env_file:
      - ../../configs/local.env
    environment:
      - APP_SVC_PORT=$LAND_APP_SVC_PORT
      - APP_SVC_DEBUG_PORT=$LAND_APP_SVC_DEBUG_PORT
      - APP_SVC_HOST=$LAND_APP_SVC_HOST
      - SVC_HOST=http://svc-auth-loc.skillum.pp.ciklum.com
    networks:
      - default
      -
  svc-auth:
    container_name: svc-auth
    image: tuiteraz/auth-app-2019-svc:latest
    env_file:
      - ../../configs/local.env
    environment:
      - POSTGRES_USER=$SKILLS_SVC_POSTGRES_USER
      - POSTGRES_PASSWORD=$SKILLS_SVC_POSTGRES_PASSWORD
      - POSTGRES_PORT=$SKILLS_SVC_POSTGRES_PORT
      - POSTGRES_HOST=$SKILLS_SVC_POSTGRES_HOST
      - POSTGRES_DB=$SKILLS_SVC_POSTGRES_DB
    depends_on:
      - auth-db
    links:
      - "auth-db:$SVC_MONGO_HOST"
    networks:
      - default
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10k"
        max-file: "3"

  auth-db:
    image: mongodb
    environment:
      - POSTGRES_USER=$SKILLS_SVC_POSTGRES_USER
      - POSTGRES_PASSWORD=$SKILLS_SVC_POSTGRES_PASSWORD
    ports:
      - "$SVC_MONGO_PORT:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
  host:

volumes:
  auth-db-data:
